name: Deploy via terraform

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Download the code 
        uses: actions/checkout@v4

      - name: List all dirs recursively
        run: ls -Rla

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Test Terrafrom version
        run: terraform version

      - name: Terrafrom init
        run: terraform init

      - name: Terrafrom validate
        run: terraform validate

      - name: Terrafrom plan
        run: terraform plan --out=my-plan.tfplan
      
      - name: Listing files
        run: |
          echo "Listing files"
          ls -l

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: my-plan.tfplan